In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5])  #we can create arrays like this in numpy
print(a)                 #indexing starts from 0
print(type(a))
print(a.shape)         #shape is give by a tuple indicating how many rows and columns 
                       #if it is one dimensional then the shape is written as (no of elements,)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
b=np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)              #it has 5 rows and 1 column

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [6]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [18]:
#Create zeros,ones, and custom array
a=np.zeros((3,3))  #we are giving the shape of the array
print(a)            #by default the array is in float
b=np.ones((3,4))
print(b)
#array of some constant 
c=np.full((2,3),5)   #here we are also passing the element which i want to pass
print(c)
#identity matrix
d=np.eye(4)       #as identity matrix is a square matrix we only have to give the size
print(d)

#random matrix
randomMatrix=np.random.random((2,3))    
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.18713989 0.76467735 0.41747987]
 [0.69428153 0.19719601 0.32315732]]


In [22]:
print(randomMatrix[ : ,1])   #here we have to give all the dimensions of the matrix
                             #here [ : ,1] means all rows and column 1

[0.76467735 0.19719601]


In [23]:
print(randomMatrix[1,1:])   #this means row 1 and all columns staring form column 1 

[0.19719601 0.32315732]


In [24]:
m=np.random.random((3,4))
print(m)

[[0.06045913 0.19553278 0.99306484 0.70085841]
 [0.47680298 0.29591593 0.66019981 0.78539111]
 [0.13336351 0.37491986 0.22391257 0.49490429]]


In [28]:
#we want change the value of m[1][1] and m[2][1] to 1
m[1,1:3]=1
print(m)

[[0.06045913 0.19553278 0.99306484 0.70085841]
 [0.47680298 1.         1.         0.78539111]
 [0.13336351 0.37491986 0.22391257 0.49490429]]


In [33]:
#set some rows and columns with any value
z=np.zeros((3,3)) 
print(z)
z[1,:]=5
z[:,-1]=7          #we can also access the last column with -1
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [34]:
#datatype
print(z.dtype)

float64


In [38]:
#we can change the data type
z=np.zeros((3,3),dtype=np.int64)
print(z)
print(z.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int64


In [42]:
#mathematical operations
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
#Elementwise addition
print(x+y)
print(np.add(x,y))
#Elementwise subtraction
print(x-y)
print(np.subtract(x,y))
#Elementwise multupication
print(x*y)
print(np.multiply(x,y))
#Elementwise division
print(x/y)
print(np.divide(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [43]:
#Elementwise square root
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [47]:
#matrix multiplication and dot product
print(x)
print(y)
print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [48]:
#Multiplication(or dot product) of vectors => scalar
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(np.dot(a,b))

70


In [49]:
print(sum(a))     #sum of all the elements of a

10


In [50]:
print(x)

[[1 2]
 [3 4]]


In [54]:
print(np.sum(x))    #sum of all the elements
print(np.sum(x,axis=0))  #sum along column
print(np.sum(x,axis=1))  #sum along row

10
[4 6]
[3 7]


In [55]:
#stacking of arrays
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [59]:
np.stack((a,b),axis=1)  # first array becomes the first column and the second array becomes the second column

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [62]:
a=np.stack((a,b),axis=0) #first array becomes the first row and the second array becomes the second row

In [67]:
# Reshape a numpy array
print(a)
print(a.reshape((4,2)))
a=a.reshape(4,2);

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [68]:
print(a.reshape(8,))

[1 2 3 4 5 6 7 8]


In [69]:
print(a.reshape(8,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [70]:
#if we don't know how many colums should be there but know that there will be 4 rows then
print(a.reshape(4,-1))  #numpy will figure it on its own

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [71]:
#if we don't know how many rows should be there but know that there will be 4 columns then
print(a.reshape(-1,4))

[[1 2 3 4]
 [5 6 7 8]]
