![](Random_numpy.jpeg)

In [1]:
import numpy as np

In [4]:
a=np.arange(10)+5             #gives a list integers in a particular range
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [6]:
np.random.shuffle(a)   #randomly shuffles the array
print(a)

[ 8 10  7  9 14 12  5 11  6 13]


In [7]:
#returns value from a standard normal distribution
a=np.random.rand(2,3)
print(a)

[[0.59682179 0.32786227 0.52378068]
 [0.82728319 0.41370951 0.67072616]]


In [9]:
a=np.random.randint(5,10,3)  #it chooses 3 random elements in range 5,10
print(a)

[7 6 7]


In [13]:
#randomly pick one element from the array
element=np.random.choice([1,2,3,4,5,6]);
print(element)

3


In [ ]:
#to get same order random number we have to plant a seed because these random number generators are pseudo random number generators
a=np.arange()